project_name: ns-cleaner
builds:
  - goos: [linux]
    goarch: [amd64]
  - goos: [darwin]
    goarch: [arm64]
  - goos: [windows]
    goarch: [amd64]

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: rookie0031
    name: declan-cli
